// ─────────────────────────────────────────────────────────────────────────────
// NIVAARAN — Demo Seed Data (SIH 26043)
// Hyper-realistic Jharkhand-specific challenges, HEI R&D projects, CSR funding,
// and IoT telemetry streams spanning all major districts & crisis zones.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  Challenge,
  Project,
  Proposal,
  TimelineEvent,
  WorkflowState,
} from './workflowTypes';

// ── Helper: generate timestamps relative to "now" ────────────────────────────
const daysAgo = (days: number): string =>
  new Date(Date.now() - days * 86_400_000).toISOString();

const hoursAgo = (hours: number): string =>
  new Date(Date.now() - hours * 3_600_000).toISOString();

// ── Seed Challenges ──────────────────────────────────────────────────────────

const SEED_CHALLENGES: Challenge[] = [
  // 1. Dhanbad — Jharia Subterranean Coal Seam Fire & Subsidence (CRITICAL)
  {
    id: 'DEMO-CH-001',
    reportId: 'NIV-2026-0001',
    title: 'Subterranean coalfield fire & toxic gas venting in Lodna Colliery',
    description: 'Ground subsidence cracks reaching 1.2m width and continuous carbon monoxide & sulphur dioxide emissions observed near Lodna 4-Pits residential quarters. Surface temperature measured at 56°C. Over 3,400 residents facing acute respiratory hazards and collapse vulnerability.',
    district: 'Dhanbad',
    block: 'Jharia',
    village: 'Lodna Colliery',
    locationCoords: { lat: 23.7460, lng: 86.4132 },
    formattedAddress: 'Lodna 4-Pits Sector, Jharia Coalfield, Dhanbad, Jharkhand',
    status: 'In Progress',
    stageNumber: 8,
    stageName: 'Stage 8: Team Formation & Project Initiation',
    category: 'Coalfire, Subsidence & Industrial Hazard',
    aiAnalysis: {
      category: 'Coalfire, Subsidence & Industrial Hazard',
      categoryCode: 'GOV-MINE',
      matchedProblem: 'Subterranean coal seam fire and toxic gas venting',
      confidenceScore: 98,
      priorityScore: 96,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 25, max: 25, reason: '3,400+ mining township residents in direct plume & collapse path' },
        economicLifeSaving:        { score: 25, max: 25, reason: 'Critical life-safety hazard with imminent subsidence collapse risk' },
        resolutionCostFeasibility: { score: 22, max: 25, reason: 'Borehole nitrogen-foam grouting and thermal InSAR telemetry feasible' },
        hazardUrgency:             { score: 24, max: 25, reason: 'Toxic CO venting and 56°C ground surface temperatures active' },
      },
      reasoning: 'Critical geotechnical and toxicological hazard. Deep underground combustion requires thermal gradient monitoring and multi-point borehole telemetry.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Mining Engineering', 'Geotechnical Engineering', 'Environmental Science'],
    },
    priorityScore: 96,
    confidenceScore: 98,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'Inspected by Dhanbad Mining Safety Directorate & DC Office. Cleared for IIT (ISM) Dhanbad prototype deployment.',
    govtValidatedBy: 'Shri A. K. Rai, Deputy Commissioner, Dhanbad',
    govtValidatedAt: daysAgo(14),
    assignedHEI: 'IIT (ISM) Dhanbad',
    assignedDept: 'Mining & Geotechnical Engineering',
    assignedProjectId: 'DEMO-PRJ-001',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },

  // 2. Giridih — Arsenic & Fluoride Toxicity in Santhal Villages (CRITICAL)
  {
    id: 'DEMO-CH-002',
    reportId: 'NIV-2026-0002',
    title: 'Severe handpump arsenic & fluoride toxicity in 18 Santhal tribal hamlets',
    description: 'Hydrogeological sampling by PHED reveals arsenic levels at 0.08 mg/L (8x WHO safe limit) and fluoride at 3.6 mg/L across 42 handpumps in Tisri block. Over 6,200 residents afflicted with dental/skeletal fluorosis and keratosis lesions.',
    district: 'Giridih',
    block: 'Tisri',
    village: 'Lokai & Baramasia',
    locationCoords: { lat: 24.5821, lng: 86.0543 },
    formattedAddress: 'Tisri Tribal Belt, Giridih District, Jharkhand',
    status: 'Prototype Active',
    stageNumber: 11,
    stageName: 'Stage 11: Prototype Development & Testing',
    category: 'Drinking Water Quality & Toxic Contamination',
    aiAnalysis: {
      category: 'Drinking Water Quality & Toxic Contamination',
      categoryCode: 'GOV-WATER',
      matchedProblem: 'Arsenic and fluoride contamination in drinking water',
      confidenceScore: 99,
      priorityScore: 95,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 25, max: 25, reason: '6,200+ tribal citizens consuming severely toxic groundwater' },
        economicLifeSaving:        { score: 25, max: 25, reason: 'Prevention of permanent crippling skeletal fluorosis & arsenicosis' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Solar-powered nano-iron adsorbent filter cartridges retrofittable on Mark-II pumps' },
        hazardUrgency:             { score: 24, max: 25, reason: 'Chronic poisoning ongoing daily at 8x safe thresholds' },
      },
      reasoning: 'Urgent public health crisis in remote tribal belt. Low-cost adsorbent nano-media required to provide immediate clean water.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Environmental Engineering', 'Chemistry', 'Biotechnology', 'Public Health'],
    },
    priorityScore: 95,
    confidenceScore: 99,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'PHED Giridih verified. IIT (ISM) Dhanbad lab filter prototype approved for Stage 11 field pilot.',
    govtValidatedBy: 'Shri Vikram Singh, DC Giridih',
    govtValidatedAt: daysAgo(28),
    assignedHEI: 'IIT (ISM) Dhanbad',
    assignedDept: 'Environmental Science & Engineering',
    assignedProjectId: 'DEMO-PRJ-002',
    createdAt: daysAgo(35),
    updatedAt: daysAgo(1),
  },

  // 3. Palamu — Severe Agricultural Drought & Aquifer Depletion (CRITICAL)
  {
    id: 'DEMO-CH-003',
    reportId: 'NIV-2026-0003',
    title: 'Severe rain-shadow agricultural drought & acute aquifer drawdown in North Koel basin',
    description: 'Consecutive 45-day dry spell led to water table plunging below 42m depth across 1,800 hectares of paddy land in Chhatarpur block. 940 tribal smallholder families facing total crop failure. Deep borewells running dry with zero surface irrigation.',
    district: 'Palamu',
    block: 'Chhatarpur',
    village: 'Mahugawan',
    locationCoords: { lat: 24.2341, lng: 84.1852 },
    formattedAddress: 'Chhatarpur Block, Palamu District, Jharkhand',
    status: 'In Progress',
    stageNumber: 9,
    stageName: 'Stage 9: R&D & Engineering Specification',
    category: 'Agricultural Drought & Aquifer Depletion',
    aiAnalysis: {
      category: 'Agricultural Drought & Aquifer Depletion',
      categoryCode: 'GOV-DROUGHT',
      matchedProblem: 'Severe agricultural drought and groundwater depletion',
      confidenceScore: 96,
      priorityScore: 91,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 23, max: 25, reason: '940 farming families and 1,800 hectares facing complete livelihood loss' },
        economicLifeSaving:        { score: 24, max: 25, reason: 'Agrarian crisis mitigation and groundwater recharge preservation' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Solar micro-drip automation and IoT piezometer telemetry networks' },
        hazardUrgency:             { score: 23, max: 25, reason: 'Current kharif season crop at critical wilting point' },
      },
      reasoning: 'Chronic rain-shadow zone vulnerability exacerbated by over-extraction. Automated micro-irrigation and aquifer telemetry needed.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Agronomy', 'Agricultural Engineering', 'Hydrology & Remote Sensing'],
    },
    priorityScore: 91,
    confidenceScore: 96,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'Joint field appraisal completed by District Agriculture Officer & BAU Ranchi. Co-funded by NTPC CSR.',
    govtValidatedBy: 'Shri Shashi Ranjan, DC Palamu',
    govtValidatedAt: daysAgo(21),
    assignedHEI: 'Birsa Agricultural University (BAU)',
    assignedDept: 'Soil & Water Conservation Engineering',
    assignedProjectId: 'DEMO-PRJ-003',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(4),
  },

  // 4. East Singhbhum — Subarnarekha Flash Flood & Culvert Siltation (HIGH)
  {
    id: 'DEMO-CH-004',
    reportId: 'NIV-2026-0004',
    title: 'Subarnarekha & Kharkai confluence flash inundation & culvert siltation',
    description: 'Depressional downpour caused 4.2m rapid river swell at Bagbera-Mango riverbanks. Storm culverts choked with industrial slag runoff, trapping 3.5 feet of stormwater across residential wards and cutting off primary roads.',
    district: 'East Singhbhum',
    block: 'Jamshedpur',
    village: 'Bagbera Colony',
    locationCoords: { lat: 22.7758, lng: 86.1436 },
    formattedAddress: 'Bagbera Riverine Belt, Jamshedpur, East Singhbhum, Jharkhand',
    status: 'In Progress',
    stageNumber: 8,
    stageName: 'Stage 8: Team Formation & Project Initiation',
    category: 'Flood Management & Urban Drainage',
    aiAnalysis: {
      category: 'Flood Management & Urban Drainage',
      categoryCode: 'GOV-FLOOD',
      matchedProblem: 'River confluence flash flooding and culvert siltation',
      confidenceScore: 97,
      priorityScore: 89,
      riskLevel: 'HIGH',
      factors: {
        populationImpact:          { score: 23, max: 25, reason: '45,000+ peri-urban residents in low-lying Bagbera-Mango catchment' },
        economicLifeSaving:        { score: 22, max: 25, reason: 'Prevention of commercial inundation and seasonal waterborne outbreaks' },
        resolutionCostFeasibility: { score: 22, max: 25, reason: 'Ultrasonic river-stage sensor nodes and self-scouring siphon gates' },
        hazardUrgency:             { score: 22, max: 25, reason: 'Monsoon depression storm cycles repeating bi-weekly' },
      },
      reasoning: 'High-density urban flood vulnerability caused by combined river swell and clogged drainage egress. Telemetry early-warning essential.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Civil Engineering', 'Hydraulics', 'Electronics & IoT'],
    },
    priorityScore: 89,
    confidenceScore: 97,
    riskLevel: 'HIGH',
    evidenceUrls: ['https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'Jamshedpur Notified Area Committee (JNAC) validated. Assigned to NIT Jamshedpur Civil & IoT Lab.',
    govtValidatedBy: 'Shri Ananya Mittal, DC East Singhbhum',
    govtValidatedAt: daysAgo(16),
    assignedHEI: 'NIT Jamshedpur',
    assignedDept: 'Civil Engineering (Water Resources)',
    assignedProjectId: 'DEMO-PRJ-004',
    createdAt: daysAgo(24),
    updatedAt: daysAgo(2),
  },

  // 5. West Singhbhum — Saranda Forest Karo River Red Mud Contamination (CRITICAL)
  {
    id: 'DEMO-CH-005',
    reportId: 'NIV-2026-0005',
    title: 'Hematite red mud slurry runoff polluting Karo river tribal drinking sources',
    description: 'Heavy rains breached opencast iron ore mine tailing bunds near Gua, discharging high-turbidity hematite red slurry (>450 NTU) into the Karo river. 14 indigenous Ho tribal settlements cutoff from safe potable water.',
    district: 'West Singhbhum',
    block: 'Noamundi',
    village: 'Gua Basti',
    locationCoords: { lat: 22.1854, lng: 85.3942 },
    formattedAddress: 'Saranda Forest Fringe, Gua, West Singhbhum, Jharkhand',
    status: 'Government Validated',
    stageNumber: 3,
    stageName: 'Stage 3: Government Validated & Prioritized',
    category: 'Industrial Mining Effluent & River Contamination',
    aiAnalysis: {
      category: 'Industrial Mining Effluent & River Contamination',
      categoryCode: 'GOV-MINE',
      matchedProblem: 'Mine tailing slurry runoff and river turbidity',
      confidenceScore: 98,
      priorityScore: 93,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 24, max: 25, reason: '14 tribal settlements completely dependent on Karo river' },
        economicLifeSaving:        { score: 24, max: 25, reason: 'Acute gastrointestinal epidemic and heavy-metal bioaccumulation prevention' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Solar-powered multi-stage coagulant-flocculation clarifier system' },
        hazardUrgency:             { score: 24, max: 25, reason: 'Turbidity exceeds 450 NTU with total loss of drinking water access' },
      },
      reasoning: 'Critical ecological and indigenous community water crisis. Requires immediate decentralized clarifier filtration and bund stabilization.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Metallurgical Engineering', 'Environmental Science', 'Chemical Engineering'],
    },
    priorityScore: 93,
    confidenceScore: 98,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'District Collector Office & State Pollution Board site visit completed. Fast-tracked for Kolhan University & NIT Jamshedpur match.',
    govtValidatedBy: 'Shri Kuldeep Choudhary, DC West Singhbhum',
    govtValidatedAt: daysAgo(6),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(6),
  },

  // 6. Latehar — Betla Elephant Corridor Crop Raiding & Human Conflict (HIGH)
  {
    id: 'DEMO-CH-006',
    reportId: 'NIV-2026-0006',
    title: 'Elephant corridor fragmentation & nocturnal crop raiding in Betla buffer zone',
    description: 'A herd of 16 Asiatic elephants displaced by railway siding construction is entering agrarian settlements nightly in Barwadih block. 120+ farming families lost ₹22 lakh of paddy crops this season with repeated near-fatal encounters.',
    district: 'Latehar',
    block: 'Barwadih',
    village: 'Betla Fringe / Kechki',
    locationCoords: { lat: 23.8731, lng: 84.0640 },
    formattedAddress: 'Betla Forest Buffer, Barwadih, Latehar, Jharkhand',
    status: 'In Progress',
    stageNumber: 8,
    stageName: 'Stage 8: Team Formation & Project Initiation',
    category: 'Wildlife Conservation & Human-Animal Conflict',
    aiAnalysis: {
      category: 'Wildlife Conservation & Human-Animal Conflict',
      categoryCode: 'GOV-WILD',
      matchedProblem: 'Elephant corridor fragmentation and human-wildlife conflict',
      confidenceScore: 95,
      priorityScore: 86,
      riskLevel: 'HIGH',
      factors: {
        populationImpact:          { score: 21, max: 25, reason: '120+ farming families facing nocturnal safety risk and crop ruin' },
        economicLifeSaving:        { score: 23, max: 25, reason: 'Preservation of agricultural livelihoods and elephant conservation' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Solar LoRa seismic & thermal acoustic elephant early-warning arrays' },
        hazardUrgency:             { score: 21, max: 25, reason: 'Nightly elephant intrusions ongoing during peak harvest' },
      },
      reasoning: 'Critical human-wildlife conflict demanding non-invasive AI bio-acoustic detection and community SMS siren triggers.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Forestry & Wildlife Science', 'Electronics & IoT', 'Remote Sensing'],
    },
    priorityScore: 86,
    confidenceScore: 95,
    riskLevel: 'HIGH',
    evidenceUrls: ['https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'DFO Latehar approved prototype intervention plan. BIT Sindri Forestry & Electronics team onboarded.',
    govtValidatedBy: 'Shri Himanshu Mohan, DC Latehar',
    govtValidatedAt: daysAgo(19),
    assignedHEI: 'BIT Sindri',
    assignedDept: 'Electronics & Forestry Ecology',
    assignedProjectId: 'DEMO-PRJ-005',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(3),
  },

  // 7. Sahibganj — Ganga Riverbank Erosion & Diara Island Submergence (CRITICAL)
  {
    id: 'DEMO-CH-007',
    reportId: 'NIV-2026-0007',
    title: 'Ganga riverbank erosion & seasonal diara island submergence',
    description: 'Intense northward meander scour of the Ganga river eroded 85 metres of fertile riverbank near Rajmahal, isolating 420 diara families and cutting off emergency river ambulance boat logistics to Sahibganj Sadar Hospital.',
    district: 'Sahibganj',
    block: 'Rajmahal',
    village: 'Kankjol Diara',
    locationCoords: { lat: 25.0489, lng: 87.8341 },
    formattedAddress: 'Rajmahal Ganga Riverbank, Sahibganj District, Jharkhand',
    status: 'In Progress',
    stageNumber: 10,
    stageName: 'Stage 10: Proposal Approved & Tranche 1 Disbursed',
    category: 'Riverbank Erosion & Disaster Inundation',
    aiAnalysis: {
      category: 'Riverbank Erosion & Disaster Inundation',
      categoryCode: 'GOV-DISASTER',
      matchedProblem: 'Ganga riverbank erosion and flood island submergence',
      confidenceScore: 97,
      priorityScore: 94,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 24, max: 25, reason: '420 diara families cut off from medical and food lifelines' },
        economicLifeSaving:        { score: 25, max: 25, reason: 'Immediate prevention of village washing-away into active river channel' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Geotextile eco-spur placement and real-time bathymetric sonar buoys' },
        hazardUrgency:             { score: 24, max: 25, reason: 'Bank erosion rate of 1.5m per day during peak monsoon discharge' },
      },
      reasoning: 'High-hazard dynamic fluvial erosion requiring bio-engineered geotextile spur defenses and river stage telemetry.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Hydraulic Engineering', 'Civil Engineering', 'Ocean & River Sciences'],
    },
    priorityScore: 94,
    confidenceScore: 97,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'District Disaster Management Cell sanctioned emergency funds. SKMU Dumka and NIT Jamshedpur assigned.',
    govtValidatedBy: 'Shri Umesh Prasad, DC Sahibganj',
    govtValidatedAt: daysAgo(22),
    assignedHEI: 'Sido Kanhu Murmu University (SKMU)',
    assignedDept: 'Earth Sciences & Hydraulic Engineering',
    assignedProjectId: 'DEMO-PRJ-006',
    createdAt: daysAgo(29),
    updatedAt: daysAgo(1),
  },

  // 8. Ranchi — Kanke Dam Inundation & Hutup School Access Cutoff (HIGH)
  {
    id: 'DEMO-CH-008',
    reportId: 'NIV-2026-0008',
    title: 'Kanke dam spillway overflow & Hutup culvert blockage flooding school access road',
    description: 'Storm backwater accumulation in Hutup Panchayat has submerged the main access road under 3.5 feet of stagnant runoff. 450 students unable to reach Government High School Hutup safely. Stagnant water breeding vector-borne diseases.',
    district: 'Ranchi',
    block: 'Kanke',
    village: 'Hutup',
    locationCoords: { lat: 23.4031, lng: 85.3208 },
    formattedAddress: 'Hutup Panchayat Main Road, Kanke, Ranchi, Jharkhand',
    status: 'In Progress',
    stageNumber: 8,
    stageName: 'Stage 8: Team Formation & Project Initiation',
    category: 'Urban Infrastructure & Drainage Flooding',
    aiAnalysis: {
      category: 'Urban Infrastructure & Drainage Flooding',
      categoryCode: 'GOV-FLOOD',
      matchedProblem: 'Culvert drainage blockage and school road flooding',
      confidenceScore: 96,
      priorityScore: 84,
      riskLevel: 'HIGH',
      factors: {
        populationImpact:          { score: 20, max: 25, reason: '450 school children and 1,200 village households affected' },
        economicLifeSaving:        { score: 21, max: 25, reason: 'Child pedestrian safety & dengue epidemic containment' },
        resolutionCostFeasibility: { score: 23, max: 25, reason: 'Automated de-siltation siphon and solar radar water level sensor' },
        hazardUrgency:             { score: 20, max: 25, reason: 'Daily school disruption and dengue threat' },
      },
      reasoning: 'Recurring seasonal drainage choke. Modular sensor-activated drainage pumps and culvert de-siltation will resolve permanently.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Civil Engineering', 'IoT & Embedded Systems', 'Urban Hydrology'],
    },
    priorityScore: 84,
    confidenceScore: 96,
    riskLevel: 'HIGH',
    evidenceUrls: ['https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'BDO Kanke inspected. BIT Mesra Civil & IoT Engineering Lab assigned to install sensor telemetry.',
    govtValidatedBy: 'Shri Rahul Sinha, DC Ranchi',
    govtValidatedAt: daysAgo(10),
    assignedHEI: 'BIT Mesra, Ranchi',
    assignedDept: 'Civil Engineering & IoT Lab',
    assignedProjectId: 'DEMO-PRJ-007',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },

  // 9. Bokaro — Fly Ash & Thermal Effluent Contamination of Konar River (HIGH)
  {
    id: 'DEMO-CH-009',
    reportId: 'NIV-2026-0009',
    title: 'Fly ash slurry pipeline rupture contaminating Konar river water intake',
    description: 'Ash pond slurry pipeline rupture discharged dense coal fly ash into Konar river tributary. River water TDS surged above 1,850 ppm, choking public drinking intake pumps serving 28,000 residents in Phusro and Bermo.',
    district: 'Bokaro',
    block: 'Bermo',
    village: 'Phusro / Dhori',
    locationCoords: { lat: 23.7712, lng: 85.8741 },
    formattedAddress: 'Konar River Stretch, Phusro, Bokaro, Jharkhand',
    status: 'Under Review',
    stageNumber: 2,
    stageName: 'Stage 2: AI Triage Complete — Awaiting Government Review',
    category: 'Thermal Power Industrial Pollution & Air/Water Quality',
    aiAnalysis: {
      category: 'Thermal Power Industrial Pollution & Air/Water Quality',
      categoryCode: 'GOV-POLLUTION',
      matchedProblem: 'Fly ash pipeline rupture and water intake contamination',
      confidenceScore: 98,
      priorityScore: 88,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 23, max: 25, reason: '28,000 residents reliant on contaminated municipal water intake' },
        economicLifeSaving:        { score: 23, max: 25, reason: 'Prevention of heavy metal toxicity and drinking water shutdown' },
        resolutionCostFeasibility: { score: 20, max: 25, reason: 'Rapid electro-coagulation ash separator and autonomous TDS telemetry' },
        hazardUrgency:             { score: 22, max: 25, reason: 'Continuous ash slurry seepage into drinking water supply' },
      },
      reasoning: 'Critical industrial environmental incident. Immediate slurry containment and automated water intake diversion required.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Environmental Engineering', 'Chemical Engineering', 'Power Systems'],
    },
    priorityScore: 88,
    confidenceScore: 98,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80'],
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(2),
  },

  // 10. Saraikela Kharsawan — Industrial Electroplating Effluent into Kharkai River (CRITICAL)
  {
    id: 'DEMO-CH-010',
    reportId: 'NIV-2026-0010',
    title: 'Untreated electroplating heavy-metal chemical discharge into Kharkai river',
    description: 'High hexavalent chromium (Cr VI) and nickel detected in stormwater runoff discharging into Kharkai River at Adityapur Phase 6. Downstream villagers report burning rashes and severe aquatic mortality.',
    district: 'Saraikela Kharsawan',
    block: 'Adityapur',
    village: 'Gamharia',
    locationCoords: { lat: 22.7937, lng: 86.1345 },
    formattedAddress: 'Adityapur Industrial Area Phase 6, Saraikela Kharsawan, Jharkhand',
    status: 'Government Validated',
    stageNumber: 3,
    stageName: 'Stage 3: Government Validated & Prioritized',
    category: 'Industrial Hazardous Chemical Effluent',
    aiAnalysis: {
      category: 'Industrial Hazardous Chemical Effluent',
      categoryCode: 'GOV-HAZMAT',
      matchedProblem: 'Industrial heavy metal electroplating chemical discharge',
      confidenceScore: 99,
      priorityScore: 94,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 24, max: 25, reason: 'Downstream river users and Gamharia village population' },
        economicLifeSaving:        { score: 25, max: 25, reason: 'Hexavalent chromium carcinogenic exposure prevention' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Electrochemical reduction cell & continuous optical ion probe' },
        hazardUrgency:             { score: 24, max: 25, reason: 'Active toxic discharge into public riverway' },
      },
      reasoning: 'Severe industrial effluent violation with carcinogen exposure risk. Prioritized for NIT Jamshedpur chemical engineering lab.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Chemical Engineering', 'Environmental Science', 'Industrial Safety'],
    },
    priorityScore: 94,
    confidenceScore: 99,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'JSPCB Regional Officer issued show-cause. R&D intervention approved for NIT Jamshedpur.',
    govtValidatedBy: 'Shri Ravi Shankar Shukla, DC Saraikela',
    govtValidatedAt: daysAgo(4),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(4),
  },

  // 11. Khunti — Lac Cultivation Pest Blight Devastation (HIGH)
  {
    id: 'DEMO-CH-011',
    reportId: 'NIV-2026-0011',
    title: 'Severe blight infestation on Kusum & Ber trees devastating tribal lac cultivation',
    description: 'Sudden outbreak of fungal blight and predatory Eublemma amabilis moth larvae attacking 2,400 lac host trees across 12 Munda tribal hamlets in Torpa. 680 farming families facing 70% income loss during peak winter crop cycle.',
    district: 'Khunti',
    block: 'Torpa',
    village: 'Diyakel',
    locationCoords: { lat: 22.9542, lng: 85.2793 },
    formattedAddress: 'Torpa Tribal Agro-Forestry Belt, Khunti District, Jharkhand',
    status: 'In Progress',
    stageNumber: 8,
    stageName: 'Stage 8: Team Formation & Project Initiation',
    category: 'Agriculture, Agro-Forestry & Tribal Livelihood',
    aiAnalysis: {
      category: 'Agriculture, Agro-Forestry & Tribal Livelihood',
      categoryCode: 'GOV-AGRI',
      matchedProblem: 'Lac host tree pest blight and fungal infection',
      confidenceScore: 95,
      priorityScore: 83,
      riskLevel: 'HIGH',
      factors: {
        populationImpact:          { score: 20, max: 25, reason: '680 tribal households dependent on lac as primary cash crop' },
        economicLifeSaving:        { score: 22, max: 25, reason: 'Preservation of ₹1.4 Crore rural agro-forestry harvest' },
        resolutionCostFeasibility: { score: 22, max: 25, reason: 'Organic bio-pesticide formulations and drone thermal canopy survey' },
        hazardUrgency:             { score: 19, max: 25, reason: 'Larval proliferation active during pupation phase' },
      },
      reasoning: 'Critical tribal livelihood threat in Jharkhand’s primary lac hub. Natural bio-control and canopy monitoring needed.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Entomology & Lac Research', 'Agronomy', 'Biotechnology'],
    },
    priorityScore: 83,
    confidenceScore: 95,
    riskLevel: 'HIGH',
    evidenceUrls: ['https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'Khunti District Administration and TRIFED verified. BAU Ranchi Lac Research unit assigned.',
    govtValidatedBy: 'Shri Lokesh Mishra, DC Khunti',
    govtValidatedAt: daysAgo(12),
    assignedHEI: 'Birsa Agricultural University (BAU)',
    assignedDept: 'Entomology & Indian Institute of Natural Resins',
    assignedProjectId: 'DEMO-PRJ-008',
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
  },

  // 12. Deoghar — Handpump Bacterial Contamination during Shravani Pilgrim Rush (HIGH)
  {
    id: 'DEMO-CH-012',
    reportId: 'NIV-2026-012',
    title: 'Deep aquifer biological pathogen contamination & dry handpump failure during pilgrim rush',
    description: 'High coliform bacterial counts (>120 CFU/100ml) identified in 19 public water points along the Shravani Mela pilgrim corridor near Mohanpur. 3 deep handpumps collapsed under high extraction stress.',
    district: 'Deoghar',
    block: 'Madhupur',
    village: 'Mohanpur Border',
    locationCoords: { lat: 24.2625, lng: 86.6452 },
    formattedAddress: 'Mohanpur Pilgrim Corridor, Deoghar District, Jharkhand',
    status: 'Submitted',
    stageNumber: 1,
    stageName: 'Stage 1: Citizen Submission',
    category: 'Public Health & Drinking Water Quality',
    aiAnalysis: {
      category: 'Public Health & Drinking Water Quality',
      categoryCode: 'GOV-HEALTH',
      matchedProblem: 'Coliform contamination and handpump mechanical failure',
      confidenceScore: 96,
      priorityScore: 87,
      riskLevel: 'HIGH',
      factors: {
        populationImpact:          { score: 23, max: 25, reason: 'Thousands of transit pilgrims and local resident communities' },
        economicLifeSaving:        { score: 23, max: 25, reason: 'Waterborne cholera/gastroenteritis epidemic prevention' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Solar inline UV-C disinfection modules and sensorized flow valves' },
        hazardUrgency:             { score: 20, max: 25, reason: 'Peak festival pilgrim congregation underway' },
      },
      reasoning: 'High-traffic pilgrim corridor water safety risk. Solar UV-C disinfection cartridges required.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Public Health & Hygiene', 'Environmental Engineering', 'Water Resources'],
    },
    priorityScore: 87,
    confidenceScore: 96,
    riskLevel: 'HIGH',
    evidenceUrls: ['https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=600&q=80'],
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(4),
  },

  // 13. Hazaribagh — Barakar River Bridge Pier Scour Undermining (CRITICAL)
  {
    id: 'DEMO-CH-013',
    reportId: 'NIV-2026-0013',
    title: 'Flash runoff undermining Barakar river bridge pier foundation on rural lifeline',
    description: 'Severe riverbed scour of 2.8m detected around Pier-3 of the Barakar bridge connecting 22 agrarian villages to Chouparan market. Structural vibrations and foundation exposure risk catastrophic collapse during peak flood currents.',
    district: 'Hazaribagh',
    block: 'Chouparan',
    village: 'Barakar Ghat',
    locationCoords: { lat: 24.3211, lng: 85.2415 },
    formattedAddress: 'Barakar River Crossing, Chouparan, Hazaribagh, Jharkhand',
    status: 'Government Validated',
    stageNumber: 3,
    stageName: 'Stage 3: Government Validated & Prioritized',
    category: 'Bridge Infrastructure & Transportation Safety',
    aiAnalysis: {
      category: 'Bridge Infrastructure & Transportation Safety',
      categoryCode: 'GOV-INFRA',
      matchedProblem: 'Bridge pier scour and structural foundation undermining',
      confidenceScore: 98,
      priorityScore: 92,
      riskLevel: 'CRITICAL',
      factors: {
        populationImpact:          { score: 23, max: 25, reason: '22 agrarian villages completely isolated if bridge collapses' },
        economicLifeSaving:        { score: 25, max: 25, reason: 'Prevention of catastrophic bridge collapse with vehicular transit' },
        resolutionCostFeasibility: { score: 20, max: 25, reason: 'Fiber-optic Bragg grating strain sensors and micro-concrete geo-jacketing' },
        hazardUrgency:             { score: 24, max: 25, reason: '2.8m scour depth exposing critical foundation footing' },
      },
      reasoning: 'Imminent structural failure on rural arterial bridge. Geotechnical reinforcement and continuous vibration telemetry required.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Structural Engineering', 'Geotechnical Engineering', 'Civil Engineering'],
    },
    priorityScore: 92,
    confidenceScore: 98,
    riskLevel: 'CRITICAL',
    evidenceUrls: ['https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80'],
    govtOfficerNote: 'Executive Engineer PWD Hazaribagh submitted site inspection report. Assigned to VBU & NIT Jamshedpur.',
    govtValidatedBy: 'Nancy Sahay, DC Hazaribagh',
    govtValidatedAt: daysAgo(5),
    createdAt: daysAgo(11),
    updatedAt: daysAgo(5),
  },

  // 14. Koderma — Abandoned Mica Open-Cast Pit Collapse Hazard (HIGH)
  {
    id: 'DEMO-CH-014',
    reportId: 'NIV-2026-0014',
    title: 'Unreclaimed abandoned mica opencast mine pit waterlogging and rim collapse hazard',
    description: 'Deep unbarricaded mica open-pit excavations filled with 35-foot deep acidic water (pH 4.8) spanning 18 hectares near residential settlement. Heavy slope erosion threatens 140 tribal houses during heavy downpours.',
    district: 'Koderma',
    block: 'Chandwara',
    village: 'Dhab Forest Rim',
    locationCoords: { lat: 24.4660, lng: 85.5990 },
    formattedAddress: 'Dhab Mica Belt, Chandwara, Koderma, Jharkhand',
    status: 'Submitted',
    stageNumber: 1,
    stageName: 'Stage 1: Citizen Submission',
    category: 'Abandoned Mine Hazard & Geotechnical Stability',
    aiAnalysis: {
      category: 'Abandoned Mine Hazard & Geotechnical Stability',
      categoryCode: 'GOV-MINE',
      matchedProblem: 'Abandoned open-cast mine pit waterlogging and rim collapse',
      confidenceScore: 95,
      priorityScore: 82,
      riskLevel: 'HIGH',
      factors: {
        populationImpact:          { score: 19, max: 25, reason: '140 tribal families living directly adjacent to collapsing pit rim' },
        economicLifeSaving:        { score: 22, max: 25, reason: 'Landslide prevention and child drowning hazard elimination' },
        resolutionCostFeasibility: { score: 21, max: 25, reason: 'Geo-grid vegetative slope stabilization and solar perimeter beacons' },
        hazardUrgency:             { score: 20, max: 25, reason: 'Pit rim receding 1.2m per monsoon season' },
      },
      reasoning: 'Geotechnical collapse risk from abandoned mica quarries. Vegetative soil reinforcement and drainage terracing needed.',
      needsHumanVerification: false,
      recommendedUniversityDepts: ['Mining Engineering', 'Geology', 'Environmental Science'],
    },
    priorityScore: 82,
    confidenceScore: 95,
    riskLevel: 'HIGH',
    evidenceUrls: ['https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80'],
    createdAt: hoursAgo(12),
    updatedAt: hoursAgo(12),
  },
];

// ── Seed Projects ────────────────────────────────────────────────────────────

const SEED_PROJECTS: Project[] = [
  // PRJ-001: Jharia Coalfield Subterranean Fire DTS & InSAR Sensor Grid
  {
    id: 'DEMO-PRJ-001',
    challengeId: 'DEMO-CH-001',
    challengeTitle: 'Subterranean coalfield fire & toxic gas venting in Lodna Colliery',
    category: 'Coalfire, Subsidence & Industrial Hazard',
    district: 'Dhanbad',
    universityId: 'IIT-ISM-DHANBAD',
    universityName: 'IIT (ISM) Dhanbad',
    facultyMentorName: 'Dr. S. K. Roy (Rock Mechanics & Mining Safety)',
    facultyEmail: 'skroy@iitism.ac.in',
    teamMembers: [
      { id: 'TM-001', name: 'Priya Sharma', departmentName: 'Mining Engineering', role: 'Team Lead & Field Investigator', skills: ['Rock mechanics', 'Borehole logging', 'Underground mining safety'] },
      { id: 'TM-002', name: 'Aditya Raj', departmentName: 'Electronics & Instrumentation', role: 'IoT & Telemetry Engineer', skills: ['Fiber-optic DTS', 'LoRaWAN gateways', 'Gas sensors (CO/SO2)'] },
      { id: 'TM-003', name: 'Rohan Soren', departmentName: 'Earth Sciences & Remote Sensing', role: 'InSAR & GIS Analyst', skills: ['Satellite InSAR deformation', 'Thermal drone mapping', 'Python GIS'] },
      { id: 'TM-004', name: 'Ankita Verma', departmentName: 'Chemical Engineering', role: 'Grouting Specialist', skills: ['Nitrogen foam inertization', 'Fly ash grout rheology', 'Lab analysis'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-001', stageNumber: 1, title: 'Surface Thermal & Gas Mapping', description: 'Deploy thermal drone scanner and multi-gas detectors across Lodna 4-Pits zone', status: 'Completed', targetDays: 7, completedAt: daysAgo(10) },
      { id: 'MS-002', stageNumber: 2, title: 'Fiber-Optic DTS Borehole Sensor Rig', description: 'Design high-temperature armored fiber-optic DTS cable for 60m borehole deployment', status: 'In Progress', targetDays: 14 },
      { id: 'MS-003', stageNumber: 3, title: 'Real-time UART/LoRa Gateway Sync', description: 'Integrate 115200 Baud local telemetry gateway with Nivaaran Super Admin dashboard', status: 'Pending', targetDays: 10 },
      { id: 'MS-004', stageNumber: 4, title: 'Nitrogen-Foam Grouting Barrier Trial', description: 'Execute localized borehole inertization trial with BCCL safety personnel', status: 'Pending', targetDays: 21 },
      { id: 'MS-005', stageNumber: 5, title: 'Community Early Warning Siren Handover', description: 'Install automated CO threshold siren linked to district DM disaster control room', status: 'Pending', targetDays: 14 },
    ],
    proposals: [],
    budgetEstimated: 650000,
    budgetApproved: 650000,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },

  // PRJ-002: Giridih Arsenic & Fluoride Nanoadsorbent Filter Cartridge
  {
    id: 'DEMO-PRJ-002',
    challengeId: 'DEMO-CH-002',
    challengeTitle: 'Severe handpump arsenic & fluoride toxicity in 18 Santhal tribal hamlets',
    category: 'Drinking Water Quality & Toxic Contamination',
    district: 'Giridih',
    universityId: 'IIT-ISM-DHANBAD',
    universityName: 'IIT (ISM) Dhanbad',
    facultyMentorName: 'Prof. Ankit Verma (Environmental Engineering)',
    facultyEmail: 'ankit.verma@iitism.ac.in',
    teamMembers: [
      { id: 'TM-005', name: 'Deepak Sahu', departmentName: 'Environmental Engineering', role: 'Team Lead', skills: ['Water treatment', 'Nano-adsorption', 'Atomic Absorption Spectrophotometry'] },
      { id: 'TM-006', name: 'Kavita Singh', departmentName: 'Chemistry', role: 'Materials Researcher', skills: ['Iron-oxide synthesis', 'Activated alumina coating', 'Lab safety'] },
      { id: 'TM-007', name: 'Arjun Mahto', departmentName: 'Mechanical Engineering', role: 'Hardware Product Designer', skills: ['Mark-II retrofit CAD', '3D additive prototyping', 'Pressure drop calc'] },
      { id: 'TM-008', name: 'Ritu Kumari', departmentName: 'Biotechnology', role: 'Water Quality Analyst', skills: ['Microbiology testing', 'Turbidity analysis', 'Heavy metal detection'] },
    ],
    status: 'Prototype Active',
    milestones: [
      { id: 'MS-006', stageNumber: 1, title: 'Comprehensive Handpump Water Baseline', description: 'AAS lab analysis of arsenic and fluoride across 42 Tisri handpumps', status: 'Completed', targetDays: 10, completedAt: daysAgo(25) },
      { id: 'MS-007', stageNumber: 2, title: 'Iron-Oxide Nano-Adsorbent Media Synthesis', description: 'Synthesise high-capacity FeOOH coated granular media in university lab', status: 'Completed', targetDays: 14, completedAt: daysAgo(12) },
      { id: 'MS-008', stageNumber: 3, title: 'Modular Cartridge Prototype Fabrication', description: 'Fabricate stainless steel 304 filter cartridge with toolless quick-swap flange', status: 'Completed', targetDays: 10, completedAt: daysAgo(3) },
      { id: 'MS-009', stageNumber: 4, title: 'Continuous Flow Breakthrough Lab Testing', description: 'Verify <10 ppb arsenic and <1.0 ppm fluoride over 10,000 litres throughput', status: 'In Progress', targetDays: 14 },
      { id: 'MS-010', stageNumber: 5, title: 'Field Pilot in 3 Santhal Hamlets', description: 'Deploy filter units at Lokai & Baramasia community handpumps with daily sampling', status: 'Pending', targetDays: 28 },
      { id: 'MS-011', stageNumber: 6, title: 'Village Jal Sahiyya Training & Handover', description: 'Train local tribal women water stewards for media regeneration & cartridge swap', status: 'Pending', targetDays: 14 },
    ],
    proposals: [],
    budgetEstimated: 520000,
    budgetApproved: 520000,
    createdAt: daysAgo(32),
    updatedAt: daysAgo(1),
  },

  // PRJ-003: Palamu Smart Solar Aquifer Telemetry & Micro-Drip System
  {
    id: 'DEMO-PRJ-003',
    challengeId: 'DEMO-CH-003',
    challengeTitle: 'Severe rain-shadow agricultural drought & acute aquifer drawdown in North Koel basin',
    category: 'Agricultural Drought & Aquifer Depletion',
    district: 'Palamu',
    universityId: 'BAU-RANCHI',
    universityName: 'Birsa Agricultural University (BAU)',
    facultyMentorName: 'Dr. Rameshwar Oraon (Soil & Water Engineering)',
    facultyEmail: 'rameshwar.oraon@bauranchi.ac.in',
    teamMembers: [
      { id: 'TM-009', name: 'Amit Murmu', departmentName: 'Agricultural Engineering', role: 'Team Lead', skills: ['Micro-irrigation design', 'Soil moisture sensors', 'Hydrology'] },
      { id: 'TM-010', name: 'Shweta Kumari', departmentName: 'Agronomy', role: 'Crop Water Modeler', skills: ['Crop evapotranspiration (ETc)', 'Drought-tolerant cultivars', 'Tribal outreach'] },
      { id: 'TM-011', name: 'Vikas Pandey', departmentName: 'Electronics & Telemetry', role: 'Firmware Engineer', skills: ['Solar MPPT', 'LoRa piezometer nodes', 'ESP32 firmware'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-012', stageNumber: 1, title: 'Aquifer Depth & Soil Moisture Audit', description: 'Map 42m groundwater drawdown and TDR soil moisture gradients in Chhatarpur', status: 'Completed', targetDays: 10, completedAt: daysAgo(15) },
      { id: 'MS-013', stageNumber: 2, title: 'Solar Smart Drip Controller R&D', description: 'Build automated valve controller triggered by sub-surface tension threshold (<30 kPa)', status: 'In Progress', targetDays: 18 },
      { id: 'MS-014', stageNumber: 3, title: 'Pilot Field Trial on 50 Hectares', description: 'Deploy micro-drip pilot with 40 tribal farmers in Mahugawan', status: 'Pending', targetDays: 30 },
    ],
    proposals: [],
    budgetEstimated: 480000,
    budgetApproved: 480000,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(4),
  },

  // PRJ-004: East Singhbhum Ultrasonic River Stage Telemetry & High-Flow Siphon
  {
    id: 'DEMO-PRJ-004',
    challengeId: 'DEMO-CH-004',
    challengeTitle: 'Subarnarekha & Kharkai confluence flash inundation & culvert siltation',
    category: 'Flood Management & Urban Drainage',
    district: 'East Singhbhum',
    universityId: 'NIT-JAMSHEDPUR',
    universityName: 'NIT Jamshedpur',
    facultyMentorName: 'Dr. V. K. Mahato (Hydraulic Engineering)',
    facultyEmail: 'vkmahato@nitjsr.ac.in',
    teamMembers: [
      { id: 'TM-012', name: 'Rahul Soren', departmentName: 'Civil Engineering', role: 'Team Lead', skills: ['HEC-RAS flood modeling', 'Culvert hydraulics', 'Structural concrete'] },
      { id: 'TM-013', name: 'Ayush Kumar Singh', departmentName: 'Electronics & Communication', role: 'IoT Lead', skills: ['Ultrasonic stage sensors', 'Cellular MQTT', 'Low-power design'] },
      { id: 'TM-014', name: 'Neha Kumari', departmentName: 'Computer Science', role: 'Fullstack & GIS', skills: ['Leaflet GIS overlays', 'Early warning broadcast algorithms', 'REST APIs'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-015', stageNumber: 1, title: 'Confluence Bathymetry & Hydrodynamic Model', description: 'HEC-RAS 2D simulation of Subarnarekha-Kharkai flood backwater curves', status: 'Completed', targetDays: 14, completedAt: daysAgo(8) },
      { id: 'MS-016', stageNumber: 2, title: 'Solar Ultrasonic Stage Sentinel Assembly', description: 'Fabricate waterproof IP68 river stage telemetry unit with dual SIM failover', status: 'In Progress', targetDays: 14 },
      { id: 'MS-017', stageNumber: 3, title: 'Self-Flushing Culvert Siphon Pilot', description: 'Install automated vortex de-silting siphon at Bagbera outflow channel', status: 'Pending', targetDays: 21 },
    ],
    proposals: [],
    budgetEstimated: 580000,
    budgetApproved: 580000,
    createdAt: daysAgo(16),
    updatedAt: daysAgo(2),
  },

  // PRJ-005: Latehar Elephant Early-Warning Seismic Array
  {
    id: 'DEMO-PRJ-005',
    challengeId: 'DEMO-CH-006',
    challengeTitle: 'Elephant corridor fragmentation & nocturnal crop raiding in Betla buffer zone',
    category: 'Wildlife Conservation & Human-Animal Conflict',
    district: 'Latehar',
    universityId: 'BIT-SINDRI',
    universityName: 'BIT Sindri',
    facultyMentorName: 'Dr. Priya Sharma (Wildlife Ecology & Electronics)',
    facultyEmail: 'priya.sharma@bitsindri.ac.in',
    teamMembers: [
      { id: 'TM-015', name: 'Aditya Kumar', departmentName: 'Forestry & Wildlife Ecology', role: 'Team Lead', skills: ['Wildlife telemetry', 'Palamu corridor tracking', 'Community liaison'] },
      { id: 'TM-016', name: 'Sneha Mishra', departmentName: 'Electronics & Communication', role: 'IoT Developer', skills: ['Seismic geophone sensors', 'LoRa mesh network', 'Edge AI'] },
      { id: 'TM-017', name: 'Rahul Oraon', departmentName: 'Computer Science', role: 'ML Engineer', skills: ['Audio bio-acoustic classifier', 'Footstep waveform analysis', 'Python'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-018', stageNumber: 1, title: 'Corridor Movement & Footprint Audit', description: 'Map 14 active elephant migratory crossing points along Betla-Barwadih boundary', status: 'Completed', targetDays: 14, completedAt: daysAgo(10) },
      { id: 'MS-019', stageNumber: 2, title: 'Buried Geophone Seismic Array Test', description: 'Calibrate seismic infrasound sensor detection of heavy pachyderm footsteps at 200m range', status: 'In Progress', targetDays: 21 },
      { id: 'MS-020', stageNumber: 3, title: 'Automated Solar Flashing Siren & SMS Trigger', description: 'Deploy 6 perimeter warning towers with trilingual village SMS dispatch', status: 'Pending', targetDays: 18 },
    ],
    proposals: [],
    budgetEstimated: 420000,
    budgetApproved: 420000,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
  },

  // PRJ-006: Sahibganj Ganga Riverbank Geotextile Eco-Spur & Sonar Buoy
  {
    id: 'DEMO-PRJ-006',
    challengeId: 'DEMO-CH-007',
    challengeTitle: 'Ganga riverbank erosion & seasonal diara island submergence',
    category: 'Riverbank Erosion & Disaster Inundation',
    district: 'Sahibganj',
    universityId: 'SKMU-DUMKA',
    universityName: 'Sido Kanhu Murmu University (SKMU)',
    facultyMentorName: 'Dr. Hemant Murmu (Fluvial Geomorphology)',
    facultyEmail: 'hemant.murmu@skmu.ac.in',
    teamMembers: [
      { id: 'TM-018', name: 'Sanjay Hansda', departmentName: 'Earth Sciences', role: 'Team Lead', skills: ['Riverbank bathymetry', 'Fluvial sediment transport', 'Santhali communication'] },
      { id: 'TM-019', name: 'Pooja Soren', departmentName: 'Civil Engineering', role: 'Geotechnical Engineer', skills: ['Geotextile mattresses', 'Rip-rap revetment design', 'Slope stability'] },
      { id: 'TM-020', name: 'Manish Kumar', departmentName: 'Electronics', role: 'Sonar Telemetry Lead', skills: ['Acoustic Doppler Current Profiler (ADCP)', 'Solar buoys', 'GPS tracking'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-021', stageNumber: 1, title: 'Bank Recession Rate & Sonar Survey', description: 'Measure 85m scour pocket using ADCP sonar and satellite optical change detection', status: 'Completed', targetDays: 14, completedAt: daysAgo(12) },
      { id: 'MS-022', stageNumber: 2, title: 'Eco-Spur Geotextile Matrix Design', description: 'Design permeable bamboo-reinforced coir-geotextile spurs to deflect main thalweg current', status: 'In Progress', targetDays: 21 },
      { id: 'MS-023', stageNumber: 3, title: 'Pilot Spur Construction & Erosion Sentinel', description: 'Construct 2 pilot spurs at Kankjol Diara with live bank vibration sensors', status: 'Pending', targetDays: 30 },
    ],
    proposals: [],
    budgetEstimated: 600000,
    budgetApproved: 600000,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(1),
  },

  // PRJ-007: Ranchi Kanke Dam Automated De-siltation & Radar Telemetry
  {
    id: 'DEMO-PRJ-007',
    challengeId: 'DEMO-CH-008',
    challengeTitle: 'Kanke dam spillway overflow & Hutup culvert blockage flooding school access road',
    category: 'Urban Infrastructure & Drainage Flooding',
    district: 'Ranchi',
    universityId: 'BIT-MESRA',
    universityName: 'BIT Mesra, Ranchi',
    facultyMentorName: 'Dr. Arvind Sinha (IoT Lab & Environmental Engineering)',
    facultyEmail: 'arvind.sinha@bitmesra.ac.in',
    teamMembers: [
      { id: 'TM-021', name: 'Ayush Kumar Singh', departmentName: 'Electronics & Communication', role: 'Team Lead', skills: ['IoT sensor telemetry', 'UART 115200 Baud communication', 'Embedded C'] },
      { id: 'TM-022', name: 'Tanvi Agarwal', departmentName: 'Civil Engineering', role: 'Hydraulics Specialist', skills: ['Drainage gradient design', 'Archimedes de-silting screw', 'CAD'] },
      { id: 'TM-023', name: 'Nikhil Tirkey', departmentName: 'Computer Science', role: 'Cloud & Telemetry Dashboard', skills: ['React', 'WebSockets', 'Telemetry log stream'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-024', stageNumber: 1, title: 'Drainage Gradient & Silt Profile Inspection', description: 'Inspect 1.2km Hutup stormwater canal and calculate peak runoff coefficient', status: 'Completed', targetDays: 7, completedAt: daysAgo(6) },
      { id: 'MS-025', stageNumber: 2, title: 'Radar Water Level Sentinel Deployment', description: 'Install millimeter-wave radar sensor with 4G solar telemetry node at culvert inlet', status: 'In Progress', targetDays: 10 },
      { id: 'MS-026', stageNumber: 3, title: 'Solar Powered De-siltation Augur Rig', description: 'Commission automatic Archimedes trash-rake to prevent vegetative culvert blockage', status: 'Pending', targetDays: 18 },
    ],
    proposals: [],
    budgetEstimated: 450000,
    budgetApproved: 450000,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },

  // PRJ-008: Khunti Tribal Lac Cultivation Bio-Pesticide & Thermal Drone Rig
  {
    id: 'DEMO-PRJ-008',
    challengeId: 'DEMO-CH-011',
    challengeTitle: 'Severe blight infestation on Kusum & Ber trees devastating tribal lac cultivation',
    category: 'Agriculture, Agro-Forestry & Tribal Livelihood',
    district: 'Khunti',
    universityId: 'BAU-RANCHI',
    universityName: 'Birsa Agricultural University (BAU)',
    facultyMentorName: 'Dr. R. N. Tiwari (Agronomy & Entomology)',
    facultyEmail: 'rntiwari@bauranchi.ac.in',
    teamMembers: [
      { id: 'TM-024', name: 'Birsa Munda', departmentName: 'Entomology & Lac Culture', role: 'Team Lead', skills: ['Lac insect life cycle', 'Bio-control of Eublemma amabilis', 'Mundari language'] },
      { id: 'TM-025', name: 'Pooja Kispotta', departmentName: 'Biotechnology', role: 'Formulation Chemist', skills: ['Neem-karanj nano-emulsion', 'Fungal antagonistic microbes', 'Bioassay'] },
      { id: 'TM-026', name: 'Ravi Prakash', departmentName: 'Agricultural Engineering', role: 'Drone Pilot & Remote Sensing', skills: ['Multispectral NDVI imaging', 'Precision drone spraying', 'Flight planning'] },
    ],
    status: 'Team Formed',
    milestones: [
      { id: 'MS-027', stageNumber: 1, title: 'Infestation Mapping & Larval Count', description: 'Sample 2,400 host trees in Torpa and isolate fungal blight strains in laboratory', status: 'Completed', targetDays: 10, completedAt: daysAgo(8) },
      { id: 'MS-028', stageNumber: 2, title: 'Organic Micro-Encapsulated Bio-Spray Formulation', description: 'Synthesise non-toxic bio-pesticide lethal to predator moths but safe for lac insects', status: 'In Progress', targetDays: 14 },
      { id: 'MS-029', stageNumber: 3, title: 'Precision Drone Canopy Spraying Demonstration', description: 'Demonstrate ultra-low volume drone spraying across 500 trees in Diyakel village', status: 'Pending', targetDays: 20 },
    ],
    proposals: [],
    budgetEstimated: 390000,
    budgetApproved: 390000,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
];

// ── Seed Proposals ───────────────────────────────────────────────────────────

const SEED_PROPOSALS: Proposal[] = [
  {
    id: 'DEMO-PROP-001',
    projectId: 'DEMO-PRJ-001',
    title: 'Distributed Fiber-Optic DTS & InSAR Deformation Monitoring for Jharia Coalfire Hazard',
    description: 'Armored fiber-optic temperature sensors combined with high-frequency satellite InSAR deformation and autonomous borehole CO/SO2 sniffers to detect catastrophic ground collapse 72 hours prior to failure.',
    approach: 'Phase 1: Drill 4 monitoring boreholes to intercept fire frontier. Phase 2: Lower armored DTS cable with continuous 1m spatial resolution. Phase 3: Sync UART 115200 Baud local gateway with Nivaaran emergency broadcast system. Phase 4: Deploy nitrogen-foam barrier to suppress high-temperature hotspots.',
    estimatedBudget: 650000,
    estimatedTimeline: '18 weeks',
    status: 'Approved',
    submittedBy: 'Priya Sharma (Team Lead, IIT ISM Dhanbad)',
    submittedAt: daysAgo(12),
    reviewNote: 'Approved by Mining Safety Directorate & District Administration. BCCL CSR grant of ₹6.50L sanctioned.',
  },
  {
    id: 'DEMO-PROP-002',
    projectId: 'DEMO-PRJ-002',
    title: 'Gravity-Fed Solar-Regenerated FeOOH Nano-Adsorbent Cartridge for Rural Mark-II Handpumps',
    description: 'Turnkey, zero-electricity gravity cartridge utilizing synthesised iron oxide (FeOOH) and activated alumina media to selectively adsorb arsenic (<10 ppb) and fluoride (<1.0 ppm) at flow rates up to 15 L/min.',
    approach: 'Phase 1: Synthesise nanoparticle media from domestic industrial precursors. Phase 2: Design quick-release 304 stainless steel cartridge fitting standard India Mark-II spout. Phase 3: 10,000L laboratory breakthrough curve validation. Phase 4: Field pilot in 3 Santhal hamlets with Jal Sahiyya training.',
    estimatedBudget: 520000,
    estimatedTimeline: '16 weeks',
    status: 'Approved',
    submittedBy: 'Deepak Sahu (Team Lead, IIT ISM Dhanbad)',
    submittedAt: daysAgo(20),
    reviewNote: 'Approved by PHED Giridih. Tata Steel Foundation CSR grant of ₹5.20L confirmed.',
  },
  {
    id: 'DEMO-PROP-003',
    projectId: 'DEMO-PRJ-004',
    title: 'Ultrasonic Stage Telemetry & High-Discharge Self-Scouring Siphon at Subarnarekha Confluence',
    description: 'Solar millimeter-wave ultrasonic river stage sensors linked to autonomous siphon discharge gates to relieve waterlogging in low-lying Bagbera and Mango wards.',
    approach: 'Phase 1: HEC-RAS 2D dynamic hydrodynamic model of confluence. Phase 2: Deploy solar radar sensors with 4G LTE-M failover telemetry. Phase 3: Construct self-scouring vortex siphon gate at arterial drain outlet. Phase 4: Integrate with SDMA Cap Alert dispatcher.',
    estimatedBudget: 580000,
    estimatedTimeline: '14 weeks',
    status: 'Approved',
    submittedBy: 'Rahul Soren (Team Lead, NIT Jamshedpur)',
    submittedAt: daysAgo(14),
    reviewNote: 'Approved by JNAC & DC East Singhbhum. Tata Steel TSRDS grant of ₹5.80L released.',
  },
];

// ── Seed Timeline Events ─────────────────────────────────────────────────────

const SEED_TIMELINE: TimelineEvent[] = [
  // Jharia Coalfire Events
  { id: 'DEMO-TL-001', entityType: 'challenge', entityId: 'DEMO-CH-001', action: 'submitted', actor: 'Kusunda Village Mukhiya', actorRole: 'Citizen', description: 'Report submitted: Subsidence cracks & CO smoke venting at Lodna 4-Pits', timestamp: daysAgo(20) },
  { id: 'DEMO-TL-002', entityType: 'challenge', entityId: 'DEMO-CH-001', action: 'ai_triage_complete', actor: 'Nivaaran AI Engine', actorRole: 'System', description: 'AI Triage: CRITICAL Priority 96/100 · Geotechnical & Toxic Hazard', timestamp: daysAgo(20) },
  { id: 'DEMO-TL-003', entityType: 'challenge', entityId: 'DEMO-CH-001', action: 'status_changed', actor: 'Shri A. K. Rai, DC Dhanbad', actorRole: 'Government Department', description: 'Government validated after joint site inspection with BCCL safety cell', previousValue: 'Under Review', newValue: 'Government Validated', timestamp: daysAgo(14) },
  { id: 'DEMO-TL-004', entityType: 'challenge', entityId: 'DEMO-CH-001', action: 'hei_matched', actor: 'Nivaaran Matching Engine', actorRole: 'System', description: 'Matched to IIT (ISM) Dhanbad (Mining & Earth Sciences) — 98% compatibility', timestamp: daysAgo(15) },
  { id: 'DEMO-TL-005', entityType: 'project',   entityId: 'DEMO-PRJ-001', action: 'created', actor: 'Dr. S. K. Roy', actorRole: 'Faculty / Mentor', description: 'R&D Project initialized with 4-member student engineering team', timestamp: daysAgo(15) },
  { id: 'DEMO-TL-006', entityType: 'proposal',  entityId: 'DEMO-PROP-001', action: 'approved', actor: 'BCCL CSR Foundation', actorRole: 'Corporate CSR Partner', description: '₹6.50L CSR grant approved. Tranche 1 (30%) disbursed.', timestamp: daysAgo(12) },
  { id: 'DEMO-TL-007', entityType: 'milestone', entityId: 'MS-001', action: 'completed', actor: 'Priya Sharma', actorRole: 'Student', description: 'Thermal drone surface survey completed across Lodna Colliery', timestamp: daysAgo(10) },

  // Giridih Arsenic Events
  { id: 'DEMO-TL-008', entityType: 'challenge', entityId: 'DEMO-CH-002', action: 'submitted', actor: 'Tisri Gram Pradhan', actorRole: 'Citizen', description: 'Report submitted: Toxic arsenic in 18 Santhal village handpumps', timestamp: daysAgo(35) },
  { id: 'DEMO-TL-009', entityType: 'challenge', entityId: 'DEMO-CH-002', action: 'status_changed', actor: 'Shri Vikram Singh, DC Giridih', actorRole: 'Government Department', description: 'PHED lab confirms 8x WHO arsenic limits. Validated for emergency HEI action.', previousValue: 'Under Review', newValue: 'Government Validated', timestamp: daysAgo(28) },
  { id: 'DEMO-TL-010', entityType: 'project',   entityId: 'DEMO-PRJ-002', action: 'created', actor: 'Prof. Ankit Verma', actorRole: 'Faculty / Mentor', description: 'IIT (ISM) Dhanbad Environmental Eng team formed', timestamp: daysAgo(32) },
  { id: 'DEMO-TL-011', entityType: 'proposal',  entityId: 'DEMO-PROP-002', action: 'approved', actor: 'Tata Steel Foundation', actorRole: 'Corporate CSR Partner', description: '₹5.20L grant approved for nano-adsorbent cartridge field pilot', timestamp: daysAgo(20) },
  { id: 'DEMO-TL-012', entityType: 'milestone', entityId: 'MS-008', action: 'completed', actor: 'Arjun Mahto', actorRole: 'Student', description: 'Modular 304 SS handpump cartridge prototype fabricated & pressure-tested', timestamp: daysAgo(3) },
  { id: 'DEMO-TL-013', entityType: 'challenge', entityId: 'DEMO-CH-002', action: 'status_changed', actor: 'System', actorRole: 'System', description: 'Advanced to Stage 11: Prototype Development & Testing', previousValue: 'In Progress', newValue: 'Prototype Active', timestamp: daysAgo(1) },

  // Palamu Drought Events
  { id: 'DEMO-TL-014', entityType: 'challenge', entityId: 'DEMO-CH-003', action: 'submitted', actor: 'Chhatarpur Kisan Samiti', actorRole: 'Citizen', description: 'Report submitted: 42m groundwater drop & crop wilting', timestamp: daysAgo(30) },
  { id: 'DEMO-TL-015', entityType: 'challenge', entityId: 'DEMO-CH-003', action: 'status_changed', actor: 'Shri Shashi Ranjan, DC Palamu', actorRole: 'Government Department', description: 'Validated as Stage 3 Priority Drought Zone', previousValue: 'Under Review', newValue: 'Government Validated', timestamp: daysAgo(21) },
  { id: 'DEMO-TL-016', entityType: 'project',   entityId: 'DEMO-PRJ-003', action: 'created', actor: 'Dr. Rameshwar Oraon', actorRole: 'Faculty / Mentor', description: 'BAU Ranchi Agricultural Engineering team assigned', timestamp: daysAgo(20) },

  // East Singhbhum Flood Events
  { id: 'DEMO-TL-017', entityType: 'challenge', entityId: 'DEMO-CH-004', action: 'submitted', actor: 'Bagbera Ward Member', actorRole: 'Citizen', description: 'Report submitted: Confluence river surge & culvert choke', timestamp: daysAgo(24) },
  { id: 'DEMO-TL-018', entityType: 'challenge', entityId: 'DEMO-CH-004', action: 'status_changed', actor: 'Shri Ananya Mittal, DC East Singhbhum', actorRole: 'Government Department', description: 'JNAC validated. High priority for monsoon flood management.', previousValue: 'Under Review', newValue: 'Government Validated', timestamp: daysAgo(16) },
  { id: 'DEMO-TL-019', entityType: 'project',   entityId: 'DEMO-PRJ-004', action: 'created', actor: 'Dr. V. K. Mahato', actorRole: 'Faculty / Mentor', description: 'NIT Jamshedpur Civil & IoT team assigned', timestamp: daysAgo(16) },

  // West Singhbhum Gua Slurry Events
  { id: 'DEMO-TL-020', entityType: 'challenge', entityId: 'DEMO-CH-005', action: 'submitted', actor: 'Gua Basti Munda Committee', actorRole: 'Citizen', description: 'Report submitted: Hematite red mud slurry in Karo river', timestamp: daysAgo(12) },
  { id: 'DEMO-TL-021', entityType: 'challenge', entityId: 'DEMO-CH-005', action: 'status_changed', actor: 'Shri Kuldeep Choudhary, DC West Singhbhum', actorRole: 'Government Department', description: 'Government validated. Kolhan Univ & NIT Jamshedpur assigned.', previousValue: 'Under Review', newValue: 'Government Validated', timestamp: daysAgo(6) },

  // Ranchi Kanke Overflow Events
  { id: 'DEMO-TL-022', entityType: 'challenge', entityId: 'DEMO-CH-008', action: 'submitted', actor: 'Hutup Panchayat Resident', actorRole: 'Citizen', description: 'Report submitted: School road submerged under 3.5ft water', timestamp: daysAgo(15) },
  { id: 'DEMO-TL-023', entityType: 'challenge', entityId: 'DEMO-CH-008', action: 'status_changed', actor: 'Shri Rahul Sinha, DC Ranchi', actorRole: 'Government Department', description: 'SDO Kanke site inspection confirmed. BIT Mesra team assigned.', previousValue: 'Under Review', newValue: 'Government Validated', timestamp: daysAgo(10) },
  { id: 'DEMO-TL-024', entityType: 'project',   entityId: 'DEMO-PRJ-007', action: 'created', actor: 'Dr. Arvind Sinha', actorRole: 'Faculty / Mentor', description: 'BIT Mesra IoT & Civil team formed', timestamp: daysAgo(10) },
];

// ── Export full seed state ───────────────────────────────────────────────────

export const createSeedData = (): WorkflowState => ({
  challenges: SEED_CHALLENGES,
  projects: SEED_PROJECTS,
  proposals: SEED_PROPOSALS,
  timelineEvents: SEED_TIMELINE,
  lastUpdated: new Date().toISOString(),
});
